### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by stuartlangridge** [liu-xiao-guo/btchat#1]
Hey: this looks like a port of the QML Bluetooth Chat example to Ubuntu phone. Did you ever get this to work? I am having problems with the QML Bluetooth on Ubuntu phone: whenever I try to send data, I receive an error `QIODevice::write: device not open`. Did you have the same problem? Or does this app work for you?

**Comment by stuartlangridge** [comment]
Ah. The problem I was having is not related to the code; it's because of a phone hardware fault. So I'll close this. Sorry to bother you.

**Comment by liu-xiao-guo** [comment]
no problem. The code is definitely working. You may find my blog at http://blog.csdn.net/ubuntutouch/article/details/51818485. I have some captured pictures there.
